(()=>{
'use strict';
const wait=fn=>document.readyState==='loading'?document.addEventListener('DOMContentLoaded',fn,{once:true}):fn();
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[x]));
function toast2(msg){try{if(typeof window.toast==='function')return window.toast(msg);const t=$('toast');if(t){t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3500)}}catch(e){console.error(e)}}
function open2(html){if(typeof window.openModal==='function')window.openModal(html);else{const m=$('modal');if(m){$('modalContent').innerHTML=html;m.classList.add('show')}}}
function close2(){if(typeof window.closeModal==='function')window.closeModal();else $('modal')?.classList.remove('show')}
function normalizePhone(p){p=String(p||'').replace(/[^0-9+]/g,'');if(p.startsWith('0'))return '+213'+p.slice(1);if(p.startsWith('213'))return '+'+p;return p}
function phoneButtons(){document.querySelectorAll('.card,.info,.admin-row').forEach(el=>{const buttons=[...el.querySelectorAll('button')];const calls=buttons.filter(b=>/اتصال|phone|tel/i.test(b.textContent+' '+(b.getAttribute('data-action')||'')));const wa=buttons.filter(b=>/whatsapp/i.test(b.textContent+' '+(b.getAttribute('data-action')||'')));calls.slice(1).forEach(b=>b.remove());wa.slice(1).forEach(b=>b.remove())})}
function ensureListingStatus(){document.querySelectorAll('.status').forEach(s=>{const v=s.textContent.trim();if(/approved|مقبول|accepted/i.test(v)&&!/تم قبول ونشر المنشور/.test(v))s.textContent='تم قبول ونشر المنشور تلقائيًا';})}
function dedupeListingInfo(){document.querySelectorAll('.card-body,.info').forEach(box=>{const seen=new Set;[...box.children].forEach(ch=>{const key=(ch.textContent||'').replace(/\s+/g,' ').trim();if(!key)return;if(seen.has(key)&&!ch.querySelector('input,select,textarea,button'))ch.remove();else seen.add(key)})});phoneButtons();ensureListingStatus()}
async function notify(userId,title,message,type='report'){try{if(!window.sb||!userId)return;await window.sb.from('notifications').insert({user_id:userId,title,message,type,is_read:false})}catch(e){console.warn('notification unavailable',e)}}
function installPhoneVerification(){const originalRegister=window.register;window.register=async function(){const name=$('rn')?.value.trim(),phone=$('rp')?.value.trim(),email=$('re')?.value.trim(),password=$('rpass')?.value;if(!name||!phone||!email||!password)return toast2('يرجى ملء جميع المعلومات');if(password.length<6)return toast2('كلمة المرور يجب أن تكون 6 أحرف على الأقل');if(!$('privacy')?.checked)return toast2('يجب الموافقة على الخصوصية');try{const {data,error}=await window.sb.auth.signUp({email,password,options:{emailRedirectTo:location.origin+location.pathname,data:{full_name:name,phone,privacy_accepted:true,privacy_accepted_at:new Date().toISOString(),terms_version:'2026-08'}}});if(error)throw error;sessionStorage.setItem('kri_phone_pending',JSON.stringify({phone,email,name}));if(data?.user&&!data.session){open2(`<div class="success"><div class="success-icon">📩</div><h2>تحقق من بريدك الإلكتروني</h2><p class="muted">أرسلنا رابط تأكيد إلى <strong>${esc(email)}</strong>.</p><button type="button" data-action="openPhoneVerify">متابعة لتأكيد الهاتف</button></div>`);return}await sendPhoneOtp(phone);return}catch(e){toast2(e.message||'تعذر إنشاء الحساب')}};
window.sendPhoneOtp=async function(phone){try{const {error}=await window.sb.auth.signInWithOtp({phone,options:{channel:'sms'}});if(error)throw error;sessionStorage.setItem('kri_phone_pending',JSON.stringify({...JSON.parse(sessionStorage.getItem('kri_phone_pending')||'{}'),phone}));open2(`<h2>📱 تأكيد رقم الهاتف</h2><p class="muted">أرسلنا رمز التحقق إلى <strong>${esc(phone)}</strong>.</p><div class="form-group"><label>رمز التحقق</label><input id="otp" inputmode="numeric" autocomplete="one-time-code" maxlength="6"></div><div class="modal-actions"><button type="button" data-action="verifyPhone">تأكيد الهاتف</button><button type="button" class="secondary" data-action="resendPhone">إعادة إرسال الرمز</button></div>`)}catch(e){toast2('لم يتم إرسال SMS. تأكد من تفعيل مزود SMS في Supabase.')}};
window.verifyPhone=async function(){const p=JSON.parse(sessionStorage.getItem('kri_phone_pending')||'{}'),token=$('otp')?.value.trim();if(!p.phone||!token)return toast2('أدخل رمز التحقق');try{const {data,error}=await window.sb.auth.verifyOtp({phone:p.phone,token,type:'sms'});if(error)throw error;sessionStorage.removeItem('kri_phone_pending');close2();toast2('تم تأكيد رقم الهاتف بنجاح ✅');if(data?.session)location.reload()}catch(e){toast2(e.message||'رمز التحقق غير صحيح')}};
window.openPhoneVerify=()=>{const p=JSON.parse(sessionStorage.getItem('kri_phone_pending')||'{}');if(!p.phone)return toast2('لا يوجد رقم هاتف قيد التأكيد');window.sendPhoneOtp(p.phone)};
window.resendPhone=()=>window.openPhoneVerify();
}
function installReportFeedback(){document.addEventListener('click',async ev=>{const b=ev.target.closest('button');if(!b)return;const text=(b.textContent||'').replace(/\s+/g,' ').trim();if(!/طلب الإثبات|طلب اثبات/.test(text))return;setTimeout(()=>{document.querySelectorAll('.status').forEach(s=>{if(/قيد|pending/i.test(s.textContent)||/طلب/.test(s.textContent))s.textContent='تم طلب الإثبات — في انتظار التأكيد'})},100);},true)}
function actionObserver(){const obs=new MutationObserver(()=>{dedupeListingInfo()});obs.observe(document.body,{subtree:true,childList:true});setTimeout(dedupeListingInfo,800);setTimeout(dedupeListingInfo,2000)}
wait(()=>{try{installPhoneVerification();installReportFeedback();actionObserver();document.addEventListener('click',e=>{const a=e.target.closest('[data-action]');if(!a)return;const act=a.dataset.action;if(act==='openPhoneVerify')window.openPhoneVerify();if(act==='verifyPhone')window.verifyPhone();if(act==='resendPhone')window.resendPhone()});}catch(e){console.error('KriDari final layer',e)}})
})();
