(()=>{
'use strict';
const wait=fn=>document.readyState==='loading'?document.addEventListener('DOMContentLoaded',fn,{once:true}):fn();
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[x]));
function toast2(msg){try{if(typeof window.toast==='function')return window.toast(msg);const t=$('toast');if(t){t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3500)}}catch(e){console.error(e)}}
function open2(html){if(typeof window.openModal==='function')window.openModal(html);else{const m=$('modal');if(m){$('modalContent').innerHTML=html;m.classList.add('show')}}}
function close2(){if(typeof window.closeModal==='function')window.closeModal();else $('modal')?.classList.remove('show')}
function phoneButtons(){document.querySelectorAll('.card,.info,.admin-row').forEach(el=>{const buttons=[...el.querySelectorAll('button')];const calls=buttons.filter(b=>/اتصال|phone|tel/i.test(b.textContent+' '+(b.getAttribute('data-action')||'')));const wa=buttons.filter(b=>/whatsapp/i.test(b.textContent+' '+(b.getAttribute('data-action')||'')));calls.slice(1).forEach(b=>b.remove());wa.slice(1).forEach(b=>b.remove())})}
function ensureListingStatus(){document.querySelectorAll('.status').forEach(s=>{const v=s.textContent.trim();if(/approved|مقبول|accepted/i.test(v)&&!/تم قبول ونشر المنشور/.test(v))s.textContent='تم قبول ونشر المنشور تلقائيًا'})}
function dedupeListingInfo(){document.querySelectorAll('.card-body,.info').forEach(box=>{const seen=new Set;[...box.children].forEach(ch=>{const key=(ch.textContent||'').replace(/\s+/g,' ').trim();if(!key)return;if(seen.has(key)&&!ch.querySelector('input,select,textarea,button'))ch.remove();else seen.add(key)})});phoneButtons();ensureListingStatus()}
function centerModals(){if(!$('kri-modal-center-fix')){const style=document.createElement('style');style.id='kri-modal-center-fix';style.textContent='.modal{position:fixed!important;inset:0!important;width:100vw!important;height:100vh!important;display:none!important;align-items:center!important;justify-content:center!important;padding:16px!important;margin:0!important;box-sizing:border-box!important;transform:none!important}.modal.show{display:flex!important;align-items:center!important;justify-content:center!important}.modal .box{position:relative!important;margin:0 auto!important;top:auto!important;left:auto!important;right:auto!important;transform:none!important;max-height:calc(100vh - 32px)!important;overflow:auto!important;width:min(950px,100%)!important}.modal[style*="display: block"]{display:flex!important;align-items:center!important;justify-content:center!important}';document.head.appendChild(style)}const m=$('modal');if(m&&!m.__centerFix){m.__centerFix=true;new MutationObserver(()=>{if(m.classList.contains('show')){m.style.setProperty('display','flex','important');m.style.setProperty('align-items','center','important');m.style.setProperty('justify-content','center','important')}else m.style.setProperty('display','none','important')}).observe(m,{attributes:true,attributeFilter:['class','style']})}}
function installPhoneVerification(){window.sendPhoneOtp=async function(phone){try{const {error}=await window.sb.auth.signInWithOtp({phone,options:{channel:'sms'}});if(error)throw error;sessionStorage.setItem('kri_phone_pending',JSON.stringify({...JSON.parse(sessionStorage.getItem('kri_phone_pending')||'{}'),phone}));open2(`<h2>📱 تأكيد رقم الهاتف</h2><p class="muted">أرسلنا رمز التحقق إلى <strong>${esc(phone)}</strong>.</p><div class="form-group"><label>رمز التحقق</label><input id="otp" inputmode="numeric" autocomplete="one-time-code" maxlength="6"></div><div class="modal-actions"><button type="button" data-action="verifyPhone">تأكيد الهاتف</button><button type="button" class="secondary" data-action="resendPhone">إعادة إرسال الرمز</button></div>`)}catch(e){toast2('لم يتم إرسال SMS. تأكد من تفعيل مزود SMS في Supabase.')}};window.verifyPhone=async function(){const p=JSON.parse(sessionStorage.getItem('kri_phone_pending')||'{}'),token=$('otp')?.value.trim();if(!p.phone||!token)return toast2('أدخل رمز التحقق');try{const {data,error}=await window.sb.auth.verifyOtp({phone:p.phone,token,type:'sms'});if(error)throw error;sessionStorage.removeItem('kri_phone_pending');close2();toast2('تم تأكيد رقم الهاتف بنجاح ✅');if(data?.session)location.reload()}catch(e){toast2(e.message||'رمز التحقق غير صحيح')}};window.openPhoneVerify=()=>{const p=JSON.parse(sessionStorage.getItem('kri_phone_pending')||'{}');if(!p.phone)return toast2('لا يوجد رقم هاتف قيد التأكيد');window.sendPhoneOtp(p.phone)};window.resendPhone=()=>window.openPhoneVerify()}
function installReportFeedback(){document.addEventListener('click',ev=>{const b=ev.target.closest('button');if(!b)return;const text=(b.textContent||'').replace(/\s+/g,' ').trim();if(!/طلب الإثبات|طلب اثبات/.test(text))return;setTimeout(()=>document.querySelectorAll('.status').forEach(s=>{if(/قيد|pending/i.test(s.textContent)||/طلب/.test(s.textContent))s.textContent='تم طلب الإثبات — في انتظار التأكيد'}),100)},true)}
function actionObserver(){const obs=new MutationObserver(()=>{dedupeListingInfo();centerModals()});obs.observe(document.body,{subtree:true,childList:true});setTimeout(dedupeListingInfo,800);setTimeout(centerModals,300);setTimeout(dedupeListingInfo,2000)}
wait(()=>{try{centerModals();installPhoneVerification();installReportFeedback();actionObserver();document.addEventListener('click',e=>{const a=e.target.closest('[data-action]');if(!a)return;const act=a.dataset.action;if(act==='openPhoneVerify')window.openPhoneVerify();if(act==='verifyPhone')window.verifyPhone();if(act==='resendPhone')window.resendPhone()})}catch(e){console.error('KriDari final layer',e)}})
})();
